#!/bin/bash
    clear
    echo -e "\033[01;34m╔══════════════════════════════════════════════╗\033[0m"
    echo -e "\033[01;34m╠══════════════════════════════════════════════╣\033[0m"
    echo -e "\033[01;34m║\E[44;1;47m             MENU SSH-PLUS PRO                \E[0m\033[0;34m║"
    echo -e "\033[01;34m╠══════════════════════════════════════════════╣\033[0m"
    echo -e "\033[01;34m║\033[0;31m[\033[1;36m01\033[1;31m]\033[1;32m ➩  \033[1;33mINSTALAR UDP-CUSTOM \033[01;34m                  ║"
    echo -e "\033[01;34m║\033[0;31m[\033[1;36m02\033[1;31m]\033[1;32m ➩  \033[1;33mABRIR MENU UDP-CUSTOM \033[01;34m                ║"
    echo -e "\033[01;34m║\033[0;31m[\033[1;36m03\033[1;31m]\033[1;32m ➩  \033[1;33mINSTALAR PROXY REVERSE-TLS \033[01;34m           ║"
    echo -e "\033[01;34m║\033[0;31m[\033[1;36m04\033[1;31m]\033[1;32m ➩  \033[1;33mINSTALAR WIREGUARD \033[01;34m                   ║"
    echo -e "\033[01;34m║\033[0;31m[\033[1;36m05\033[1;31m]\033[1;32m ➩  \033[1;33mINSTALAR OPENVPN-PRO \033[01;34m                 ║"
    echo -e "\033[01;34m║\033[0;31m[\033[1;36m06\033[1;31m]\033[1;32m ➩  \033[1;33mINSTALAR WS-EPRO \033[01;34m                     ║"
    echo -e "\033[01;34m║\033[0;31m[\033[1;36m07\033[1;31m]\033[1;32m ➩  \033[1;33mINSTALAR PROXY-GOLANG \033[01;34m                ║"
    echo -e "\033[01;34m║\033[0;31m[\033[1;36m08\033[1;31m]\033[1;32m ➩  \033[1;33mINSTALAR PSIPHON \033[01;34m                     ║"
    echo -e "\033[01;34m║\033[0;31m[\033[1;36m09\033[1;31m]\033[1;32m ➩  \033[1;33mUTILIZAR VPS-OTIMIZADOR \033[01;34m              ║"
    echo -e "\033[01;34m║\033[0;31m[\033[1;36m10\033[1;31m]\033[1;32m ➩  \033[1;33mINSTALAR HYSTERIA-PRO \033[01;34m                ║"
    echo -e "\033[01;34m║\033[0;31m[\033[1;36m00\033[1;31m]\033[1;32m ➩  \033[1;33mSAIR \033[01;34m                                 ║"
    echo -e "\033[01;34m╠══════════════════════════════════════════════╝\033[0m"
			tput civis
			echo -ne "\033[1;34m╰━━━━━━━━❪\033[1;32mSELECIONE UMA OPÇÃO\033[1;33m\033[1;31m\033[1;37m":; read x
			case $x in
			1 | 01)
			clear
                        sudo wget https://raw.githubusercontent.com/thefather12/UDP-PRO/main/install.sh; chmod +x install.sh; ./install.sh
			;;
                        2 | 02)
			udp
			;;
                        3 | 03)
                        sudo apt install curl -y && bash <(curl -s https://raw.githubusercontent.com/Azumi67/Reverse_tls/main/go.sh)
                        ;;
                        4 | 04)
                        bash <(curl -Ls https://raw.githubusercontent.com/Azumi67/FRP-Wireguard/main/wire2.sh --ipv4)
                        ;;
                        5 | 05)
                        bash <(curl -sL https://raw.githubusercontent.com/PhoenixxZ2023/OpenVPN/master/openvpn-install.sh)
                        ;;
                        6 | 06)
                        bash <(curl -sL https://raw.githubusercontent.com//PhoenixxZ2023/ws-epro/main/install.sh)
                        ;;
			7 | 07)
                        GoLang.sh
                        ;;
                        8 | 08)
                        psiphon.sh
                        ;;
                        9 | 09)
                        apt install curl -y && bash <(curl -s https://raw.githubusercontent.com/opiran-club/VPS-Optimizer/main/optimizer.sh --ipv4)
                        ;;
                        10 | 10)
                        wget https://github.com/thefather12/UDPHISTERIA/raw/main/install.sh; chmod +x install.sh; ./install.sh
                        ;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpção invalida !\033[0m"
			sleep 2
			;;
			esac
		done
	}
	menub2
}
