#!/bin/bash

print_menu() {
    clear
    echo -e "\033[1;31m╔════════════════════════════════════════════════════╗"
    echo -e "║                \033[5;34;47m MENU SSH-PLUS PRO \033[1;33m                  ║"
    echo -e "╠════════════════════════════════════════════════════╣"
    echo -e "║  \033[1;34m[ \033[1;37m01 \033[1;34m] ➩ \033[1;37mINSTALAR UDP-CUSTOM                       ║"
    echo -e "║  \033[1;34m[ \033[1;37m02 \033[1;34m] ➩ \033[1;37mABRIR MENU UDP-CUSTOM                    ║"
    echo -e "║  \033[1;34m[ \033[1;37m03 \033[1;34m] ➩ \033[1;37mINSTALAR UDP-HYSTERIA (udph)             ║"
    echo -e "║  \033[1;34m[ \033[1;37m04 \033[1;34m] ➩ \033[1;37mINSTALAR SSL TUNNEL PRO                  ║"
    echo -e "║  \033[1;34m[ \033[1;37m05 \033[1;34m] ➩ \033[1;37mINSTALAR WS-EPRO                        ║"
    echo -e "║  \033[1;34m[ \033[1;37m06 \033[1;34m] ➩ \033[1;37mINSTALAR PROXY-GOLANG                   ║"
    echo -e "║  \033[1;34m[ \033[1;37m07 \033[1;34m] ➩ \033[1;37mINSTALAR PSIPHON                       ║"
    echo -e "║  \033[1;34m[ \033[1;37m08 \033[1;34m] ➩ \033[1;37mINSTALAR SLOWDNS                       ║"
    echo -e "║  \033[1;34m[ \033[1;37m09 \033[1;34m] ➩ \033[1;37mINSTALAR HYSTERIA-PRO                  ║"
    echo -e "║  \033[1;34m[ \033[1;37m00 \033[1;34m] ➩ \033[1;37mSAIR  \033[1;32m<\033[1;33m<\033[1;31m<                   ║"
    echo -e "╚════════════════════════════════════════════════════╝"
    tput civis
    echo -ne "\033[1;31m╰━━━━━━━━❪\033[1;32mSELECIONE UMA OPÇÃO\033[1;33m\033[1;31m\033[1;37m : ";
    read option
    tput cnorm
    clear
}

install_udp_custom() {
    clear
    sudo wget https://raw.githubusercontent.com/thefather12/UDP-PRO/main/install.sh && chmod +x install.sh && ./install.sh
}

open_udp_menu() {
    udp
}

install_udp_hysteria() {
    rm -f install.sh
    apt-get update -y
    apt-get upgrade -y
    wget "https://raw.githubusercontent.com/prjkt-nv404/UDP-Hysteria/main/install.sh" -O install.sh >/dev/null 2>&1
    chmod 777 install.sh
    ./install.sh
    rm -f install.sh && udph
}

install_ssl_tunnel_pro() {
    bash <(curl -sL https://raw.githubusercontent.com/PhoenixxZ2023/SSL-PRO/main/stunnel5.sh)
}

install_ws_epro() {
    bash <(curl -sL https://raw.githubusercontent.com/PhoenixxZ2023/ws-epro/main/Netcolvip.bin)
}

install_proxy_golang() {
    GoLang.sh
}

install_psiphon() {
    psiphon.sh
}

install_slowdns() {
    slowdns.sh
}

install_hysteria_pro() {
    bash <(curl -Ls https://raw.githubusercontent.com/missuo/Hysteria2/main/hy2.sh)
}

main() {
    while true; do
        print_menu

        case $option in
            1) install_udp_custom ;;
            2) open_udp_menu ;;
            3) install_udp_hysteria ;;
            4) install_ssl_tunnel_pro ;;
            5) install_ws_epro ;;
            6) install_proxy_golang ;;
            7) install_psiphon ;;
            8) install_slowdns ;;
            9) install_hysteria_pro ;;
            0) clear && exit ;;
            *) echo -e "\033[1;31mOpção inválida!\033[0m" && sleep 2 ;;
        esac
    done
}

main
