#!/bin/bash

# Calcula o número de CPUs e converte para hexadecimal
CPUS_HEX=$(echo "obase=16;2^$(nproc)-1" | bc)

# Define o valor hexadecimal no arquivo rps_cpus da interface de rede eth0
echo $CPUS_HEX > /sys/class/net/eth0/queues/rx-0/rps_cpus

# Define o tamanho da hash para 16384 no módulo nf_conntrack
echo 16384 > /sys/module/nf_conntrack/parameters/hashsize

# Define o número de flow IDs por fila de recebimento para 16384 na interface eth0
echo 16384 > /sys/class/net/eth0/queues/rx-0/rps_flow_cnt

# Define o Timestamp Counter (TSC) como a fonte de relógio atual para o sistema
echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource

# Desativa as páginas transparentes enormes (THP) nas configurações de gerenciamento de memória do kernel
echo never > /sys/kernel/mm/transparent_hugepage/enabled

# Instala o pacote htop
sudo apt install htop -y

# Encontra o PID do processo com base no nome
pid=$(pgrep -f "nome_do_processo")

# Verifica se o PID foi encontrado
if [ -n "$pid" ]; then
    # Define a afinidade da CPU para o processo encontrado
    taskset -c 0 -p $pid

    # Limita o uso da CPU pelo processo encontrado a 50%
    cpulimit -p $pid -l 50
fi

# Atualiza o sistema
sudo apt update && sudo apt upgrade -y

# Instala o pacote perf
sudo apt install linux-tools-common -y

# Analisa o uso da CPU com perf
perf record -a -g -- sleep 30
perf report
