#!/bin/bash

_lvk=$(wget -qO- https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/versao)
IP=$(wget -qO- ipv4.icanhazip.com)
IP2=$(wget -qO- http://whatismyip.akamai.com/)

ipdovps="$IP"
if [ "$IP" != "$IP2" ]; then
    ipdovps="$IP2"
fi
echo -e "$ipdovps" >/etc/IP

lst=$1
lst1=$2
lst2=$3
key1=$4
key2="crz"

echo -e "America/Sao_Paulo" >/etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime >/dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata >/dev/null 2>&1

if [ -z "$lst1" ]; then
    rm -rf $_Ink/list >/dev/null 2>&1
    cat /dev/null >~/.bash_history
    history -c
    exit 0
fi

mkdir -p /etc/SSHPlus/{v2ray,senha,userteste,.tmp} /etc/bot/{info-users,arquivos,revenda,suspensos} /etc/rec

echo -e 'by: @KIRITO_SSH' >/usr/lib/sshplus
cp /usr/lib/sshplus "$lst2/licence"
cp /usr/lib/sshplus /etc/SSHPlus/.tmp/crazy

netstat -nplt | grep -qw 'apache2' && sed -i "s/Listen 80/Listen 81/g" /etc/apache2/ports.conf && service apache2 restart
grep -q "#Port 22" /etc/ssh/sshd_config && sed -i "s;#Port 22;Port 22;" /etc/ssh/sshd_config && service ssh restart

sed -i '/^PasswordAuthentication/d' /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >>/etc/ssh/sshd_config

_dir1='/bin'
_dir2='/etc/SSHPlus'

rm -f $_dir2/{ShellBot.sh,cabecalho,open.py,proxy.py,wsproxy.py}

_mdls=("addhost" "ajuda" "alterarlimite" "alterarsenha" "apache2menu" "auto-reboot.sh" "tcptweaker.sh" "checkers" "utili" "multi" "check" "chuser" "limit" "rps_cpu" "attscript" "Autobackup" "backup_mail.sh" "badvpn" "badpro" "badpro1" "badvpn2" "badvpn3" "banner" "bashtop" "ddos" "blocksite" "blockt" "blockuser" "bot" "botssh" "cabecalho" "conexao" "criarteste" "criarusuario" "delhost" "delscript" "detalhes" "dns-netflix.sh" "droplimiter" "expcleaner" "ban.sh" "fr" "GoLang.sh" "infousers" "inst-botteste" "initcheck" "instsqd" "limiter" "menu" "menub" "menub2" "menuudp" "mudardata" "mtuning" "multi" "onlineapp" "open.py" "otimizar" "painelv2ray" "prissh" "prnet.sh" "proxydt" "proxy.py" "psiphon.sh" "reiniciarservicos" "reiniciarsistema" "remover" "senharoot" "ShellBot.sh" "slowdns" "speedtest" "sshmonitor" "swapmemory" "trafegototal" "trojan-go" "uexpired" "userbackup" "velocity" "verifatt" "verifbot" "v2raymanager" "webmin.sh" "websocket.sh" "wireguard.sh" "wsproxy.py" "pkill.sh")

for _arq in "${_mdls[@]}"; do
    wget -c -P $_dir1 https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Modulos/$_arq
    chmod +x $_dir1/$_arq
done

mv $_dir1/{cabecalho,bot,open.py,proxy.py,wsproxy.py} $_dir2

_arq_host="/etc/hosts"
_host=("d1n212ccp6ldpw.cloudfront.net" "dns.whatsapp.net" "portalrecarga.vivo.com.br/recarga" "navegue.vivo.com.br/controle/" "navegue.vivo.com.br/pre/" "www.whatsapp.net" "/SSHPLUS?")

for host in "${_host[@]}"; do
    grep -qw "$host" $_arq_host || sed -i "3i\127.0.0.1 $host" $_arq_host
done

if [ ! -e /etc/autostart ]; then
    echo '#!/bin/bash
clear
#INICIO AUTOMATICO' >/etc/autostart
    chmod +x /etc/autostart
else
    ps x | grep -q "bot_plus" && wget -qO- https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Install/ShellBot.sh
    ps x | grep 'dmS' | grep -v 'grep' | awk {'print $1'} | xargs -r -I {} screen -r -S "{}" -X quit
    screen -wipe >/dev/null
    echo '#!/bin/bash
clear
#INICIO AUTOMATICO' >/etc/autostart
    chmod +x /etc/autostart
fi

crontab -r >/dev/null 2>&1
(crontab -l 2>/dev/null; echo "@daily /bin/verifatt"; echo "@reboot /etc/autostart"; echo "* * * * * /etc/autostart"; echo "0 */6 * * * /bin/uexpired") | crontab -

echo "$_lvk" | awk '{print $2}' >/bin/versao
cp /bin/versao /home/sshplus

wget -q https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Install/jq-linux64
chmod +x jq-linux64 && mv jq-linux64 $(command -v jq)

service cron restart >/dev/null 2>&1
service ssh restart >/dev/null 2>&1
[ -d /var/www/html/openvpn ] && service apache2 restart >/dev/null 2>&1

rm -rf "$lst1/list"

mkdir -p /opt/sshplus
touch /opt/sshplus/sshplus

cd /etc/SSHPlus/ && { wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Modulos/WebSocket; wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Modulos/pub.key; wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Modulos/priv.pem; chmod 777 WebSocket; cd $HOME; }
cd /etc/SSHPlus/ && { wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Modulos/proxydt; chmod 777 proxydt; cd $HOME; }
